# group_vars/auroradb.yml
# ---
# default variables for hosts in the "auroradb" group

aurora_cluster_security_groups:
  - "{{ vpc_security_group_ids['vpc'] }}"
aurora_cluster_port: 3306
aurora_cluster_availability_zones:
  - "{{ aws_region }}a"
  - "{{ aws_region }}b"
  - "{{ aws_region }}c"
